# Generated by Django 3.2.3 on 2021-05-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_ticketmodel_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='ticket_status',
            new_name='status',
        ),
    ]
