# Generated by Django 3.2.3 on 2021-05-25 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0006_alter_ticketmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='ticket_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='ticket_completed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='ticket_submitted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
