# Generated by Django 3.2.3 on 2021-05-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20210525_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
