# Generated by Django 3.2.3 on 2021-05-26 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0011_alter_ticketmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='ticket_invalid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_invaild', to=settings.AUTH_USER_MODEL),
        ),
    ]
