# Generated by Django 3.2.3 on 2021-05-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_ticketmodel_ticket_invalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='ticket_invalid',
        ),
    ]
